### PR TITLE
feat(reset password): user should be able to reset password

### PR DESCRIPTION
**Pull request by joelmugaya**
#### What does the PR do?
- Adds endpoints for a user to reset his/her password.
#### Description of Task to be completed?
- add password reset URLs
- configure Django fixtures
- add a database table to store reset tokens
- add methods to handle password reset functionality
- send reset token to user email
- add functions to update the password
- add tests

#### How should this be manually tested?
/api/reset_password/
```
{
	"email": "3dnamargarita@gmail.com"
}
```
/api/reset_password/<token>/
```
{
	"password": "987654321",
	"confirm_password": "987654321"
}
```

[#165273473](https://www.pivotaltracker.com/story/show/165273473)

### CODE REVIEW

**Review by mwinel — CHANGES_REQUESTED** [review]
Why is it that this branch has no deployments?

**Review by mwinel — APPROVED** [review]

**Comment by joelmugaya** [comment]
It is going to be deployed in a minute

**Review by 3Nakajugo — APPROVED** [review]

**Review by mwinel — APPROVED** [review]
This is ready for a merge.

**Review by archibishop — APPROVED** [review]
@joelmugaya LGTM I am merging this.

**Pull request merged**
