### PR TITLE
#165273459 Upgrade django version

### PR DESCRIPTION
**Pull request by mwinel**
### **What does this PR do?**
This PR upgrades the setup django version from 1.1 to 2.1.
- Install Django 2.1
- Upgrade django-cors-middleware to 1.3.1
- Upgrade django-extensions to 2.1.6
- Upgrade djangorestframework to 3.9.2
- Change urls from regex to paths

### **How to test it?**
Make migrations, run the server and try out the following endpoints in postman.

- `http://127.0.0.1:8000/api/users/` for signup or registration.
- `http://127.0.0.1:8000/api/users/login/` for user login.
- `http://127.0.0.1:8000/admin/` to access the app admin side.

### **What are the relevant user stories**
[#165273459](https://www.pivotaltracker.com/story/show/165273459)

@engjames @KabohaJeanMark @joelmugaya @sanya-kenneth @3Nakajugo @archibishop

### CODE REVIEW

**Review by joelmugaya — APPROVED** [review]

**Review by KabohaJeanMark — APPROVED** [review]
Good work following the naming conventions as per the Engineering playbook.
I like the fact that you properly switched from regular expressions to path and dealt with the migrations errors.

**Review by engjames — COMMENTED** [review]
Nice work @mwinel but it could be better if you remove commented code in your settings.py

**Review by 3Nakajugo — CHANGES_REQUESTED** [review]
Goodwork on the upgrade. But I see you have commented code.
image

**Review by 3Nakajugo — APPROVED** [review]

**Review by sanya-kenneth — APPROVED** [review]
Good work upgrading the project dependencies.

**Review by archibishop — APPROVED** [review]
LGTM @mwinel Good work here.

**Pull request merged**
