### PR TITLE
#165273466 Deploy to heroku

### PR DESCRIPTION
**Pull request by joelmugaya**
#### What does this PR do?
Configures app to be deployed on Heroku.
#### Description of Task to be completed?
- create heroku account
- create heroku pipe lines
- configure app for heroku
- test app on heroku.
#### How should this be manually tested?
- https://inviticus-review-pr-4.herokuapp.com.
#### What are the relevant pivotal tracker stories?
Add two variables to the enviroment DB=postgres and ALLOWED_HOSTS=anyvalue
[Starts #165273466](https://www.pivotaltracker.com/story/show/165273466)

#### Reviewers
@mwinel @engjames @sanya-kenneth @3Nakajugo @KabohaJeanMark

### CODE REVIEW

**Comment by mwinel** [comment]
Great job but why is the branch failing to be deployed?

**Comment by joelmugaya** [comment]
@mwinel there are a few things that I am fixing. Though even when I am done we shall be deploying manually because of the 5apps limit on the heroku account

**Review by mwinel — APPROVED** [review]
All the available endpoints work well on heroku. But you need to edit the PR description with the appropriate heroku app links.

**Review by 3Nakajugo — CHANGES_REQUESTED** [review]
hi @joelmugaya the link provided on the PR doesn't work. Is it the right link ?

**Review by 3Nakajugo — APPROVED** [review]

**Comment by archibishop** [comment]
@joelmugaya You are missing the app.json file that is responsible for the review apps. Please add it here .

**Comment by archibishop** [comment]
@joelmugaya Grant me access to `heroku` so i can check out the pipeline. Add the link to your pr description.

**Review by archibishop — APPROVED** [review]
LGTM @joelmugaya Good work here.

**Pull request merged**
